### ISSUE TITLE
Analyzer failed, error: failed to get user defined project path, error: failed to get target definition map, error: failed to read target defintion map, error: Pod::DSLError

### ISSUE THREAD

**Issue by eman6576** [bitrise-steplib/steps-project-scanner#31]
Hi,

When setting up a new app that uses Cocoapods, I get this error in the validation step:
<img width="1154" alt="screen shot 2017-02-20 at 1 11 49 pm" src="https://cloud.githubusercontent.com/assets/16155920/23137112/2cd1beea-f76e-11e6-8766-6a379e7f3b3f.png">

I'm not sure what I am doing wrong at this step. Or because Cocoapods is used, I would need to do manual configuration instead?

**Comment by godrei** [comment]
Hi @eman6576 ,
sorry for my late response and thanks for the report!

May i ask you which Cocoapods version are you using locally?

As a workaround you can add your project with manual config, however this is an issue in the scanner, i will have a look ASAP!

**Comment by godrei** [comment]
Closing as we did not receive a reply - @eman6576  please let us know if we can help with anything and we'll reopen this issue!
