### ISSUE TITLE
add support for `[build|settings].gradle.kts` 

### ISSUE THREAD

**Issue by trevjonez** [bitrise-steplib/steps-project-scanner#57]
Android library project in this case.

```
├── build.gradle.kts
├── freetype
│   ├── build.gradle.kts
│   ├── CMakeLists.txt
│   └── src
│       ├── androidTest
│       └── main
├── gradle
│   ├── scan.gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle.properties
├── gradlew
├── gradlew.bat
├── scan_result
└── settings.gradle.kts

7 directories, 10 files
[18:33:25] Saving outputs:
[18:33:25]   scan result: /bitrise/src/scan_result/result.json
[18:33:25] No known platform detected
```

**Comment by tamasbazs** [comment]
Hi @trevjonez ,
Thanks for your feature request! I escalated your feature request for review and we will update you once I get any info about it 😉

**Comment by dawidhyzy** [comment]
I have the same issue 😞

**Comment by es0329** [comment]
Same issue for me. 😞

**Comment by lszucs** [comment]
Hi @trevjonez,

We have implemented Gradle Kotlin DSL support, you should be able to autoscan your projects on bitrise.io.

For doing a local scan you'll have to update your bitrise cli plugins (`$ bitrise plugin update`).

**Comment by trevjonez** [comment]
Going to close this, I have not been on a bitrise project for some time now so have been unable to validate.
