### ISSUE TITLE
iOS scanner does not look at .xcconfig files

### ISSUE THREAD

**Issue by robinkunde** [bitrise-steplib/steps-project-scanner#82]
The scanner checks .xcodeproj files for the string "SDKROOT = iphoneos" to determine if there are iOS build targets. However, some or all of the build settings for a target can be located in xcconfig files and the scanner doesn't appear to touch those files at all, causing the scanner to fail in cases where the SDKROOT is not located in the .xcodeproj file.

**Comment by non-binary** [comment]
Hi @robinkunde,

Thank you for reporting this to us. I have created a JIRA ticket internally to track progress on this. We will let you know once this has been fixed.

Kind regards and stay healthy,
Luna
